package fr.mantastudio.gtfs.types;

public enum RouteType {
  // GTFS Official Documentation: https://developers.google.com/transit/gtfs/reference/extended-route-types
  
  // RAILWAY SERVICES
  RAILWAY_SERVICE(100),
  HIGH_SPEED_RAILWAY_SERVICE(101),
  RAILWAY_BIG_LINES(102),
  INTERREGIONAL_RAILWAY_SERVICE(103),
  CARS_TRANSPORT_RAILWAY_SERVICE(104),
  SLEEPER_RAILWAY_SERVICE(105),
  REGIONAL_RAILWAY_SERVICE(106),
  TOURIST_SERVICE_RAILWAY(107),
  RAILWAY_SHUTTLE(108),
  SUBURB_RAILWAY(109),
  SUBSTITUTION_RAILWAY_SERVICE(110),
  SPECIAL_RAILWAY_SERVICE(111),
  TRUCKS_TRANSPORT_RAILWAY_SERVICE(112),
  RAILWAY_SERVICE_ALL_CATEGORIES(113),
  INTERNATIONAL_RAILWAY_SERVICE(114),
  VEHICLES_TRANSPORT_RAILWAY_SERVICE(115),
  RACK_RAILWAY_SERVICE(116),
  ADDITIONAL_RAILWAY_SERVICE(117),
  // COACH SERVICES
  COACH_SERVICE(200),
  INTERNATIONAL_COACH_SERVICE(201),
  NATIONAL_COACH_SERVICE(202),
  COACH_SHUTTLE_SERVICE(203),
  REGIONAL_COACH_SERVICE(204),
  SPECIAL_COACH_SERVICE(205),
  SIGHTSEEING_TOUR_COACH_SERVICE(206),
  TOURISTS_COACH_SERVICE(207),
  SUBURB_COACH_SERVICE(208),
  COACH_SERVICE_ALL_CATEGORIES(209),
  // OTHER RAIL SERVICES
  URBAN_RAILWAY_SERVICE(400),
  METROPOLITAN_RAILWAY_SERVICES(401),
  UNDERGROUND_TRANSPORT_SERVICE(402),
  // A second URBAN_RAILWAY_SERVICE with ID 403 has been removed to avoid the duplication
  URBAN_RAILWAY_SERVICE_ALL_CATEGORIES(404),
  MONORAIL(405),
  // BUS SERVICES
  BUS_SERVICE(700),
  REGIONAL_BUS_SERVICE(701),
  EXPRESS_BUS_SERVICE(702),
  SERVING_STOPS_BUS_SERVICE(703),
  LOCAL_BUS_SERVICE(704),
  NOCTURNAL_BUS_SERVICE(705),
  POSTAL_COACH_SERVICE(706),
  SPECIALS_REQUIREMENTS_PERSONS_BUS_SERVICE(707),
  DISABLED_PERSONS_BUS_SERVICE(708),
  DAS_DISABLED_PERSONS_BUS_SERVICE(709),
  PANORAMIC_BUS(710),
  SHUTTLE_BUS_SERVICE(711),
  SCHOLAR_BUS(712),
  PUBLIC_AND_SCHOLAR_BUS(713),
  RAIL_REPLACEMENT_BUS_SERVICE(714),
  ON_DEMAND_BUS_TRANSPORT_SERVICE(715),
  BUS_SERVICE_ALL_CATEGORIES(716),
  // TROLLEYBUS SERVICE
  TROLLEYBUS_SERVICE(800),
  // TRAMWAY SERVICES
  TRAMWAY_SERVICE(900),
  URBAN_TRALWAY_SERVICE(901),
  LOCAL_TRAMWAY_SERVICE(902),
  REGIONAL_TRAMWAY_SERVICE(903),
  TOURIST_TRAMWAY_SERVICE(904),
  SHUTTLE_TRAMWAY_SERVICE(905),
  TRAMWAY_SERVICE_ALL_CATEGORIES(906),
  // OTHERS TRANSPORT SERVICES
  FLUVIAL_TRANSPORT_SERVICE(1000),
  AERIAL_TRANSPORT_SERVICE(1100),
  FERRY_SERVICE(1200),
  CABLE_CAR_SERVICE(1300),
  FUNICULAR_SERVICE(1400),
  // TAXIS SERVICES
  TAXIS_SERVICE(1500),
  COMMUNAL_TAXIS_SERVICE(1501),
  FLUVIAL_TAXIS_SERVICE(1502),
  RAILWAY_TAXIS_SERVICE(1503),
  VELOTAXI_SERVICE(1504),
  MANAGED_TAXIS_SERVICE(1505),
  INDIVIDUALS_VEHICLES_RENT_SERVICE(1506),
  TAXIS_SERVICE_ALL_CATEGORIES(1507),
  MISC_SERVICE(1700),
  CARRIAGE(1702);

  private int id;

  RouteType(int id) {
    this.id = id;
  }

  public int getId() {
    return id;
  }

  public RouteType getRouteTypeFromID(int raw_id) {
    RouteType r;
    for (RouteType type : values()) {
      if (type.getId() == raw_id) {
        r = type;
      }
    }
    return r;
  }
}
